"""
File: data_points.py
Work Package: AP2
Responsible Engineer: Engineer A
Purpose: OPC-UA NodeIds for REAL_SPS mode and payload envelope helper. Fake/demo values are generated by project.shared.simulation.ProcessSimulator.
"""
from __future__ import annotations

from project.shared.simulation.payload_builder import build_sps_payload, now_iso

__all__ = ["NODE_IDS", "build_payload", "now_iso"]


def _node(name: str) -> str:
    return f'ns=3;s="Datenbaustein_Prozessvariablen"."{name}"'


NODE_IDS: dict[str, str] = {
    "Aktueller_Schritt": _node("aktueller_schritt"),
    "K1_Temperatur": _node("K1_Temperatur"),
    "K1_Füllstand_OK": _node("K1_Füllstand_OK"),
    "K2_Temperatur": _node("K2_Temperatur"),
    "K2_Füllstand": _node("K2_Füllstand"),
    "K3_Temperatur": _node("K3_Temperatur"),
    "K3_Füllstand": _node("K3_Füllstand"),
    "K3_MinimalerFüllstand": _node("K3_MinimalerFüllstand"),
    "K3_MaximalerFüllstand": _node("K3_MaximalerFüllstand"),
    "MobilerSensor_Temperatur": _node("MobilerSensor_Temperatur"),
    "Durchfluss_NachgussMaische": _node("Durchfluss_NachgussMaische"),
    "emergency_stop": _node("emergency_stop"),
    "sensor_ok": _node("sensor_ok"),
    "acknowledge": _node("acknowledge"),
}


def build_payload(
    values: dict,
    source: str = "REAL_SPS",
    publisher_mode: str = "REAL",
    connection_status: str = "CONNECTED",
    sps_endpoint: str = "",
    simulation_phase: str = "LIVE",
) -> dict:
    return build_sps_payload(
        values,
        source=source,
        publisher_mode=publisher_mode,
        connection_status=connection_status,
        simulation_phase=simulation_phase,
        sps_endpoint=sps_endpoint,
    )
