# src/storage/data_points.py
# -*- coding: utf-8 -*-

"""
OPC-UA data point configuration for the brewing digital twin.

This file transforms Engineer A's node concept into a machine-readable
configuration used by the database and OPC-UA collector.
"""

DATA_POINTS = [
    {
        "name": "Aktueller_Schritt",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."Aktueller_Schritt"',
        "data_type": "Int16",
        "unit": None,
        "component": "SYSTEM",
        "category": "process_state",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Central SPS process step for FSM and API.",
    },
    {
        "name": "Durchfluss_NachgussMaische",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."Durchfluss_NachgussMaische"',
        "data_type": "Float",
        "unit": "l/min",
        "component": "FLOW_PATH",
        "category": "flow",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Required for transfer and lautering plausibility.",
    },

    # K1 – Nachgussbehälter
    {
        "name": "K1_Temperatur",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K1_Temperatur"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K1",
        "category": "temperature",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "K1 = Nachgussbehälter temperature.",
    },
    {
        "name": "K1_Füllstand_Voll",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K1_Füllstand_Voll"',
        "data_type": "Boolean",
        "unit": "bool",
        "component": "K1",
        "category": "level",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Boolean full-level status.",
    },
    {
        "name": "K1_Temperatur_SollwertObereGrenze",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K1_Temperatur_SollwertObereGrenze"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K1",
        "category": "temperature_limit",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "context",
        "poll_interval_s": 60.0,
        "is_required": 1,
        "is_context": 1,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Upper temperature limit for K1.",
    },
    {
        "name": "K1_Temperatur_SollwertUntereGrenze",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K1_Temperatur_SollwertUntereGrenze"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K1",
        "category": "temperature_limit",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "context",
        "poll_interval_s": 60.0,
        "is_required": 1,
        "is_context": 1,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Lower temperature limit for K1.",
    },

    # K2 – Maischebehälter
    {
        "name": "K2_Temperatur",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K2_Temperatur"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K2",
        "category": "temperature",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "K2 = Maischebehälter temperature.",
    },
    {
        "name": "K2_Füllstand",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K2_Füllstand"',
        "data_type": "Float",
        "unit": "Liter",
        "component": "K2",
        "category": "level",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Processed level/quantity value.",
    },
    {
        "name": "K2_Füllstand_Voll",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K2_Füllstand_Voll"',
        "data_type": "Boolean",
        "unit": "bool",
        "component": "K2",
        "category": "level",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Boolean full-level status.",
    },
    {
        "name": "K2_Temperatur_SollwertObereGrenze",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K2_Temperatur_SollwertObereGrenze"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K2",
        "category": "temperature_limit",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "context",
        "poll_interval_s": 60.0,
        "is_required": 1,
        "is_context": 1,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Upper temperature limit for K2.",
    },
    {
        "name": "K2_Temperatur_SollwertUntereGrenze",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K2_Temperatur_SollwertUntereGrenze"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K2",
        "category": "temperature_limit",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "context",
        "poll_interval_s": 60.0,
        "is_required": 1,
        "is_context": 1,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Lower temperature limit for K2.",
    },

    # K3 – Läuterbehälter
    {
        "name": "K3_Temperatur",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K3_Temperatur"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K3",
        "category": "temperature",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "K3 = Läuterbehälter temperature.",
    },
    {
        "name": "K3_Füllstand",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K3_Füllstand"',
        "data_type": "Float",
        "unit": "Liter",
        "component": "K3",
        "category": "level",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "to_check",
        "validation_note": "Live value previously implausible. Use carefully.",
    },
    {
        "name": "K3_Temperatur_SollwertObereGrenze",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K3_Temperatur_SollwertObereGrenze"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K3",
        "category": "temperature_limit",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "context",
        "poll_interval_s": 60.0,
        "is_required": 1,
        "is_context": 1,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Upper temperature limit for K3.",
    },
    {
        "name": "K3_Temperatur_SollwertUntereGrenze",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."K3_Temperatur_SollwertUntereGrenze"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K3",
        "category": "temperature_limit",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "context",
        "poll_interval_s": 60.0,
        "is_required": 1,
        "is_context": 1,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Lower temperature limit for K3.",
    },
    {
        "name": "K3_MaximalerFüllstand",
        "node_id": 'ns=3;s="Datenbaustein_Prozessparametrierung"."K3_MaximalerFüllstand"',
        "data_type": "Float",
        "unit": "Liter",
        "component": "K3",
        "category": "level_limit",
        "source_block": "DB3_ProcessParameters",
        "poll_group": "context",
        "poll_interval_s": 60.0,
        "is_required": 1,
        "is_context": 1,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Upper level limit for K3.",
    },
    {
        "name": "K3_MinimalerFüllstand",
        "node_id": 'ns=3;s="Datenbaustein_Prozessparametrierung"."K3_MinimalerFüllstand"',
        "data_type": "Float",
        "unit": "Liter",
        "component": "K3",
        "category": "level_limit",
        "source_block": "DB3_ProcessParameters",
        "poll_group": "context",
        "poll_interval_s": 60.0,
        "is_required": 1,
        "is_context": 1,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Lower level limit for K3.",
    },

    # K4 – Gär-/Reservebereich
    {
        "name": "MobilerSensor_Temperatur",
        "node_id": 'ns=3;s="Datenbaustein_Prozessvariablen"."MobilerSensor_Temperatur"',
        "data_type": "Float",
        "unit": "°C",
        "component": "K4",
        "category": "temperature",
        "source_block": "DB1_ProcessVariables",
        "poll_group": "dynamic",
        "poll_interval_s": 1.0,
        "is_required": 1,
        "is_context": 0,
        "use_in_fsm": 1,
        "use_in_api": 1,
        "use_in_anomaly": 1,
        "validation_status": "plausible",
        "validation_note": "Temperature node for fermentation/reserve area.",
    },

    # Optional actuators
    {
        "name": "Pumpe",
        "node_id": 'ns=3;s="Pumpe"',
        "data_type": "Boolean",
        "unit": "bool",
        "component": "PUMP",
        "category": "actuator_output",
        "source_block": "PLC_Outputs",
        "poll_group": "optional",
        "poll_interval_s": 1.0,
        "is_required": 0,
        "is_context": 0,
        "use_in_fsm": 0,
        "use_in_api": 1,
        "use_in_anomaly": 0,
        "validation_status": "optional_verified",
        "validation_note": "Only SPS output status, not physical feedback.",
    },
]